### ISSUE TITLE
Suggestion: Provide a SMART on FHIR capabilities statement for the fhir-proxy

### ISSUE THREAD

**Issue by rmharrison** [microsoft/fhir-proxy#4]
Re: http://hl7.org/fhir/smart-app-launch/conformance/index.html#core-capabilities

Because it's unclear from the README.md whether both EHR launch (launch-ehr) and stand-alone (launch-standalone) launch sequences are supported.

Specifically applications, such as the CMS Patient Accss API, will require the stand-alone launch sequence in combnation with other specific capabilities. Listing the SMART capabilities will help FHIR developers triage fhir-proxy for deeper evaluation.

**Comment by Kedar782** [comment]
@rmharrison 
Did you get any workaround for EHR Launch using this proxy?
I basically got the standalone launch working using this proxy.
I'm using https://github.com/Microsoft/fhir-server/samples/apps/SmartLauncher for the app launcher and created a new app for EHR launch because the scopes style is different from the standalone patient launch.
If you got the EHR launch working using this proxy, please tell me how you made it work.

Thanks in advanced.
